/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BulmaCard {
    'cardImage': string;
    'cardImagePlaceholder': string;
    'mediaImage': string;
    'mediaImagePlaceholder': string;
    'mediaSubTitle': string;
    'mediaTitle': string;
  }
  interface BulmaCardAttributes extends StencilHTMLAttributes {
    'cardImage'?: string;
    'cardImagePlaceholder'?: string;
    'mediaImage'?: string;
    'mediaImagePlaceholder'?: string;
    'mediaSubTitle'?: string;
    'mediaTitle'?: string;
  }

  interface BulmaMenu {
    'data': Object;
  }
  interface BulmaMenuAttributes extends StencilHTMLAttributes {
    'data'?: Object;
  }

  interface BulmaModal {
    'isActive': boolean;
  }
  interface BulmaModalAttributes extends StencilHTMLAttributes {
    'isActive'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BulmaCard': Components.BulmaCard;
    'BulmaMenu': Components.BulmaMenu;
    'BulmaModal': Components.BulmaModal;
  }

  interface StencilIntrinsicElements {
    'bulma-card': Components.BulmaCardAttributes;
    'bulma-menu': Components.BulmaMenuAttributes;
    'bulma-modal': Components.BulmaModalAttributes;
  }


  interface HTMLBulmaCardElement extends Components.BulmaCard, HTMLStencilElement {}
  var HTMLBulmaCardElement: {
    prototype: HTMLBulmaCardElement;
    new (): HTMLBulmaCardElement;
  };

  interface HTMLBulmaMenuElement extends Components.BulmaMenu, HTMLStencilElement {}
  var HTMLBulmaMenuElement: {
    prototype: HTMLBulmaMenuElement;
    new (): HTMLBulmaMenuElement;
  };

  interface HTMLBulmaModalElement extends Components.BulmaModal, HTMLStencilElement {}
  var HTMLBulmaModalElement: {
    prototype: HTMLBulmaModalElement;
    new (): HTMLBulmaModalElement;
  };

  interface HTMLElementTagNameMap {
    'bulma-card': HTMLBulmaCardElement
    'bulma-menu': HTMLBulmaMenuElement
    'bulma-modal': HTMLBulmaModalElement
  }

  interface ElementTagNameMap {
    'bulma-card': HTMLBulmaCardElement;
    'bulma-menu': HTMLBulmaMenuElement;
    'bulma-modal': HTMLBulmaModalElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
